import Writer from "code-block-writer";

export function renderExports(writer?: Writer) {
  writer ||= new Writer({ indentNumberOfSpaces: 2 });
  return writer
    .writeLine(`// Generated by openapi-ts-gen. DO NOT EDIT`)
    .writeLine(`/* eslint-disable */`)
    .writeLine(`export * from './client';`)
    .writeLine(`export * from './schemas';`)
    .toString();
}
